[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Nautilus = "ðŸ“˜"
# smile emoji
MyNiceProgram = "ðŸ˜›"

# i3 / Xwayland
[aliases.class]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

# Sway only
[aliases.app_id]
"^firefox$" = "Firefox"

# i3 only
[aliases.instance]
"open.spotify.com" = "Spotify"

# Both i3 and sway
[aliases.name]

[general]
separator = " î‚± "
split_at = ":"
empty_label = "ðŸŒ•"
display_property = "instance" # class, instance, name
default_icon = "ï„‘"

[options]
remove_duplicates = false
no_names = false
no_icon_names = false
focus_fix = false
