[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Nautilus = "ðŸ“˜"
# smile emoji
MyNiceProgram = "ðŸ˜›"

[aliases]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

[general]
separator = " î‚± "
default_icon = "ï„‘"
wm_property = "class"

[options]
remove_duplicates = false
no_names = false
no_icon_names = false
