[icons]
# font awesome
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
Alacritty = "ï„ "
Termite = "ï„ "
Thunderbird = "ïƒ "
Gpick = "ï”¿"
Nautilus = "ðŸ“˜"
# smile emoji
MyNiceProgram = "ðŸ˜›"

[aliases.class]
TelegramDesktop = "Telegram"
"Org\\.gnome\\.Nautilus" = "Nautilus"

[aliases.instance]
"open.spotify.com" = "Spotify"

[aliases.name]

[general]
separator = " î‚± "
default_icon = "ï„‘"
split_at = ":"
empty_label = "ðŸŒ•"
display_property = "instance" # class, instance, name

[options]
remove_duplicates = false
no_names = false
no_icon_names = false
